/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/asia_building.glb --types 
Author: Solarliu (https://sketchfab.com/jacky15621419)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asia-building-a3f45195b01f48ff9f687d3ceac52b82
Title: Asia Building
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { GLTFAction } from "../../types/gltf";

type GLTFResult = GLTF & {
  nodes: {
    polySurface3488_concrete_021_0: THREE.Mesh
    polySurface3488_concrete_fine1_0: THREE.Mesh
    polySurface3489_concrete_022_0: THREE.Mesh
    polySurface3489_rooftop_01_0: THREE.Mesh
    polySurface3490_concrete_023_0: THREE.Mesh
    polySurface3490_rooftop_011_0: THREE.Mesh
    pPlane199_rooftop_012_0: THREE.Mesh
    pPlane200_rooftop_013_0: THREE.Mesh
    pCube118_rooftop_014_0: THREE.Mesh
    pPlane198_rooftop_015_0: THREE.Mesh
    pCube117_rooftop_016_0: THREE.Mesh
    pPlane197_rooftop_017_0: THREE.Mesh
    group26_rooftop_018_0: THREE.Mesh
    pCube116_rooftop_019_0: THREE.Mesh
    pCube119_rooftop_0110_0: THREE.Mesh
    pCube121_rooftop_0111_0: THREE.Mesh
    pPlane201_rooftop_0112_0: THREE.Mesh
    pCube122_rooftop_0113_0: THREE.Mesh
    pCube123_rooftop_0114_0: THREE.Mesh
    pCube124_rooftop_0115_0: THREE.Mesh
    pCube120_rooftop_0116_0: THREE.Mesh
    pPlane199_2_rooftop_0117_0: THREE.Mesh
    pPlane200_2_rooftop_0118_0: THREE.Mesh
    pCube118_2_rooftop_0119_0: THREE.Mesh
    pPlane198_2_rooftop_0120_0: THREE.Mesh
    pCube117_2_rooftop_0121_0: THREE.Mesh
    pPlane197_2_rooftop_0122_0: THREE.Mesh
    group26_2_rooftop_0123_0: THREE.Mesh
    pCube116_2_rooftop_0124_0: THREE.Mesh
    pCube119_2_rooftop_0125_0: THREE.Mesh
    pCube121_2_rooftop_0126_0: THREE.Mesh
    pPlane201_2_rooftop_0127_0: THREE.Mesh
    pCube122_2_rooftop_0128_0: THREE.Mesh
    pCube123_2_rooftop_0129_0: THREE.Mesh
    pCube124_2_rooftop_0130_0: THREE.Mesh
    pCube120_2_rooftop_0131_0: THREE.Mesh
    pPlane199_3_rooftop_0132_0: THREE.Mesh
    pPlane200_3_rooftop_0133_0: THREE.Mesh
    pCube118_3_rooftop_0134_0: THREE.Mesh
    pPlane198_3_rooftop_0135_0: THREE.Mesh
    pCube117_3_rooftop_0136_0: THREE.Mesh
    pPlane197_3_rooftop_0137_0: THREE.Mesh
    group26_3_rooftop_0138_0: THREE.Mesh
    pCube116_3_rooftop_0139_0: THREE.Mesh
    pCube119_3_rooftop_0140_0: THREE.Mesh
    pCube121_3_rooftop_0141_0: THREE.Mesh
    pCube122_3_rooftop_0142_0: THREE.Mesh
    pCube123_3_rooftop_0143_0: THREE.Mesh
    pCube124_3_rooftop_0144_0: THREE.Mesh
    apartment_02_fine_concrete_fine_0: THREE.Mesh
    apartment_02_fine_build_01_0: THREE.Mesh
    apartment_02_fine_concrete_02_0: THREE.Mesh
    apartment_02_fine_concrete_0: THREE.Mesh
  }
  materials: {
    ['concrete_02.1']: THREE.MeshStandardMaterial
    ['concrete_fine.1']: THREE.MeshStandardMaterial
    ['concrete_02.2']: THREE.MeshStandardMaterial
    rooftop_01: THREE.MeshStandardMaterial
    ['concrete_02.3']: THREE.MeshStandardMaterial
    ['rooftop_01.1']: THREE.MeshStandardMaterial
    ['rooftop_01.2']: THREE.MeshStandardMaterial
    ['rooftop_01.3']: THREE.MeshStandardMaterial
    ['rooftop_01.4']: THREE.MeshStandardMaterial
    ['rooftop_01.5']: THREE.MeshStandardMaterial
    ['rooftop_01.6']: THREE.MeshStandardMaterial
    ['rooftop_01.7']: THREE.MeshStandardMaterial
    ['rooftop_01.8']: THREE.MeshStandardMaterial
    ['rooftop_01.9']: THREE.MeshStandardMaterial
    ['rooftop_01.10']: THREE.MeshStandardMaterial
    ['rooftop_01.11']: THREE.MeshStandardMaterial
    ['rooftop_01.12']: THREE.MeshStandardMaterial
    ['rooftop_01.13']: THREE.MeshStandardMaterial
    ['rooftop_01.14']: THREE.MeshStandardMaterial
    ['rooftop_01.15']: THREE.MeshStandardMaterial
    ['rooftop_01.16']: THREE.MeshStandardMaterial
    ['rooftop_01.17']: THREE.MeshStandardMaterial
    ['rooftop_01.18']: THREE.MeshStandardMaterial
    ['rooftop_01.19']: THREE.MeshStandardMaterial
    ['rooftop_01.20']: THREE.MeshStandardMaterial
    ['rooftop_01.21']: THREE.MeshStandardMaterial
    ['rooftop_01.22']: THREE.MeshStandardMaterial
    ['rooftop_01.23']: THREE.MeshStandardMaterial
    ['rooftop_01.24']: THREE.MeshStandardMaterial
    ['rooftop_01.25']: THREE.MeshStandardMaterial
    ['rooftop_01.26']: THREE.MeshStandardMaterial
    ['rooftop_01.27']: THREE.MeshStandardMaterial
    ['rooftop_01.28']: THREE.MeshStandardMaterial
    ['rooftop_01.29']: THREE.MeshStandardMaterial
    ['rooftop_01.30']: THREE.MeshStandardMaterial
    ['rooftop_01.31']: THREE.MeshStandardMaterial
    ['rooftop_01.32']: THREE.MeshStandardMaterial
    ['rooftop_01.33']: THREE.MeshStandardMaterial
    ['rooftop_01.34']: THREE.MeshStandardMaterial
    ['rooftop_01.35']: THREE.MeshStandardMaterial
    ['rooftop_01.36']: THREE.MeshStandardMaterial
    ['rooftop_01.37']: THREE.MeshStandardMaterial
    ['rooftop_01.38']: THREE.MeshStandardMaterial
    ['rooftop_01.39']: THREE.MeshStandardMaterial
    ['rooftop_01.40']: THREE.MeshStandardMaterial
    ['rooftop_01.41']: THREE.MeshStandardMaterial
    ['rooftop_01.42']: THREE.MeshStandardMaterial
    ['rooftop_01.43']: THREE.MeshStandardMaterial
    ['rooftop_01.44']: THREE.MeshStandardMaterial
    concrete_fine: THREE.MeshStandardMaterial
    build_01: THREE.MeshStandardMaterial
    concrete_02: THREE.MeshStandardMaterial
    concrete: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function AsiaBuilding(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/asia_building.glb') as object as GLTFResult
  return (
    <group {...props} dispose={null} userData={{isInteractable: true}}>
      <group position={[-30, 0, 219.986]}>
        <mesh geometry={nodes.polySurface3488_concrete_021_0.geometry} material={materials['concrete_02.1']} />
        <mesh geometry={nodes.polySurface3488_concrete_fine1_0.geometry} material={materials['concrete_fine.1']} />
      </group>
      <group position={[-30, 0, 219.986]}>
        <mesh geometry={nodes.polySurface3489_concrete_022_0.geometry} material={materials['concrete_02.2']} />
        <mesh geometry={nodes.polySurface3489_rooftop_01_0.geometry} material={materials.rooftop_01} />
      </group>
      <group position={[-30, 0, 219.986]}>
        <mesh geometry={nodes.polySurface3490_concrete_023_0.geometry} material={materials['concrete_02.3']} />
        <mesh geometry={nodes.polySurface3490_rooftop_011_0.geometry} material={materials['rooftop_01.1']} />
      </group>
      <group position={[-1.84, 0, -59.225]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.pPlane199_rooftop_012_0.geometry} material={materials['rooftop_01.2']} position={[-30, 3.078, 160.691]} />
        <mesh geometry={nodes.pPlane200_rooftop_013_0.geometry} material={materials['rooftop_01.3']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube118_rooftop_014_0.geometry} material={materials['rooftop_01.4']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane198_rooftop_015_0.geometry} material={materials['rooftop_01.5']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube117_rooftop_016_0.geometry} material={materials['rooftop_01.6']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane197_rooftop_017_0.geometry} material={materials['rooftop_01.7']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.group26_rooftop_018_0.geometry} material={materials['rooftop_01.8']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube116_rooftop_019_0.geometry} material={materials['rooftop_01.9']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube119_rooftop_0110_0.geometry} material={materials['rooftop_01.10']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube121_rooftop_0111_0.geometry} material={materials['rooftop_01.11']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane201_rooftop_0112_0.geometry} material={materials['rooftop_01.12']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube122_rooftop_0113_0.geometry} material={materials['rooftop_01.13']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube123_rooftop_0114_0.geometry} material={materials['rooftop_01.14']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube124_rooftop_0115_0.geometry} material={materials['rooftop_01.15']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube120_rooftop_0116_0.geometry} material={materials['rooftop_01.16']} position={[-30, 0, 159.986]} />
      </group>
      <group position={[0, 0, 60]}>
        <mesh geometry={nodes.pPlane199_2_rooftop_0117_0.geometry} material={materials['rooftop_01.17']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane200_2_rooftop_0118_0.geometry} material={materials['rooftop_01.18']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube118_2_rooftop_0119_0.geometry} material={materials['rooftop_01.19']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane198_2_rooftop_0120_0.geometry} material={materials['rooftop_01.20']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube117_2_rooftop_0121_0.geometry} material={materials['rooftop_01.21']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane197_2_rooftop_0122_0.geometry} material={materials['rooftop_01.22']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.group26_2_rooftop_0123_0.geometry} material={materials['rooftop_01.23']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube116_2_rooftop_0124_0.geometry} material={materials['rooftop_01.24']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube119_2_rooftop_0125_0.geometry} material={materials['rooftop_01.25']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube121_2_rooftop_0126_0.geometry} material={materials['rooftop_01.26']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pPlane201_2_rooftop_0127_0.geometry} material={materials['rooftop_01.27']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube122_2_rooftop_0128_0.geometry} material={materials['rooftop_01.28']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube123_2_rooftop_0129_0.geometry} material={materials['rooftop_01.29']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube124_2_rooftop_0130_0.geometry} material={materials['rooftop_01.30']} position={[-30, 0, 159.986]} />
        <mesh geometry={nodes.pCube120_2_rooftop_0131_0.geometry} material={materials['rooftop_01.31']} position={[-30, 0, 159.986]} />
      </group>
      <group position={[-30, 0, 219.986]}>
        <mesh geometry={nodes.pPlane199_3_rooftop_0132_0.geometry} material={materials['rooftop_01.32']} />
        <mesh geometry={nodes.pPlane200_3_rooftop_0133_0.geometry} material={materials['rooftop_01.33']} />
        <mesh geometry={nodes.pCube118_3_rooftop_0134_0.geometry} material={materials['rooftop_01.34']} />
        <mesh geometry={nodes.pPlane198_3_rooftop_0135_0.geometry} material={materials['rooftop_01.35']} />
        <mesh geometry={nodes.pCube117_3_rooftop_0136_0.geometry} material={materials['rooftop_01.36']} />
        <mesh geometry={nodes.pPlane197_3_rooftop_0137_0.geometry} material={materials['rooftop_01.37']} />
        <mesh geometry={nodes.group26_3_rooftop_0138_0.geometry} material={materials['rooftop_01.38']} />
        <mesh geometry={nodes.pCube116_3_rooftop_0139_0.geometry} material={materials['rooftop_01.39']} />
        <mesh geometry={nodes.pCube119_3_rooftop_0140_0.geometry} material={materials['rooftop_01.40']} />
        <mesh geometry={nodes.pCube121_3_rooftop_0141_0.geometry} material={materials['rooftop_01.41']} />
        <mesh geometry={nodes.pCube122_3_rooftop_0142_0.geometry} material={materials['rooftop_01.42']} />
        <mesh geometry={nodes.pCube123_3_rooftop_0143_0.geometry} material={materials['rooftop_01.43']} />
        <mesh geometry={nodes.pCube124_3_rooftop_0144_0.geometry} material={materials['rooftop_01.44']} />
      </group>
      <mesh geometry={nodes.apartment_02_fine_concrete_fine_0.geometry} material={materials.concrete_fine} />
      <mesh geometry={nodes.apartment_02_fine_build_01_0.geometry} material={materials.build_01} />
      <mesh geometry={nodes.apartment_02_fine_concrete_02_0.geometry} material={materials.concrete_02} />
      <mesh geometry={nodes.apartment_02_fine_concrete_0.geometry} material={materials.concrete} />
    </group>
  )
}

useGLTF.preload('/asia_building.glb')
